#!/usr/bin/bash

if [ $# -eq 0 ]
 then 
 echo 'no argument supplied'
 exit 1;
fi

proj_dir="$(pwd)/$1";

if [ -d "$proj_dir" ]; then  
    echo "project found .. at $proj_dir";
      cd $proj_dir;
      echo "activating";
      source env/bin/activate;
      cd;
      cd $proj_dir;
else 
	mkdir -pv $proj_dir;
	cd $proj_dir;
	python3 -m venv env;
	source env/bin/activate;
	     cd;
      cd $proj_dir;
      echo "act" > .env
      ln -s ../py/env ./env -vr
fi
    
