#!/usr/bin/bash

fm="/home/pannet1";
to="/media/pannet1/FAT32/latest";

if [ -d "$to" ]; then
    echo "copying ... Personal"
    rsync --archive --size-only --update --delete --stats $fm/Personal $to/
    echo "copying ... Archive"
    rsync --archive --size-only --update --delete --stats --exclude 'tmp' --exclude 'vendor' --exclude 'composer.lock' --exclude 'node_modules' $fm/Archive $to/
fi
