#!/usr/bin/bash
echo creditaccess
rsync --archive --update --delete --force --stats --exclude 'tmp' --exclude 'vendor' --exclude 'composer.lock' /var/www/html/creditaccess /home/pannet1/Backup/hosting/home/
echo kkk
rsync --archive --update --delete --force --stats --exclude 'tmp' --exclude 'vendor' --exclude 'composer.lock' /var/www/html/kkk /home/pannet1/Backup/hosting/home/
echo srestates
rsync --archive --update --delete --force --stats --exclude 'tmp' --exclude 'vendor' --exclude 'composer.lock' /var/www/html/srestates /home/pannet1/Backup/hosting/home/
echo swethaag
rsync --archive --update --delete --force --stats --exclude 'tmp' --exclude 'vendor' --exclude 'composer.lock' /var/www/html/swethaag /home/pannet1/Backup/hosting/home/
echo ecomsense
rsync --archive --update --delete --force --stats --exclude 'tmp' --exclude 'vendor' --exclude 'composer.lock' /var/www/html/ecomsense /run/media/pannet1/FAT32/latest/Programs/php/
echo ecomsense
rsync --archive --update --delete --force --stats --exclude 'tmp' --exclude 'vendor' --exclude 'composer.lock' /var/www/html/ecomsense /run/media/pannet1/FAT32/latest/Programs/php/
echo phpmyadmin
rsync --archive --update --delete --force --stats --exclude 'tmp' --exclude 'vendor' --exclude 'composer.lock' /var/www/html/phpmyadmin /run/media/pannet1/FAT32/latest/Programs/php/
echo creditaccess
rsync --archive --update --delete --force --stats --exclude 'tmp' --exclude 'vendor' --exclude 'composer.lock' /var/www/html/creditaccess /run/media/pannet1/FAT32/latest/Programs/php/
echo test2trade
rsync --archive --update --delete --force --stats --exclude 'tmp' --exclude 'vendor' --exclude 'composer.lock' /var/www/html/test2trade /run/media/pannet1/FAT32/latest/Programs/php/
echo httrack
rsync --archive --update --delete --force --stats --exclude 'tmp' --exclude 'vendor' --exclude 'composer.lock' /var/www/html/httrack /run/media/pannet1/FAT32/latest/Programs/php/
echo httrack
rsync --archive --update --delete --force --stats --exclude 'tmp' --exclude 'vendor' --exclude 'composer.lock' /var/www/html/httrack /run/media/pannet1/FAT32/latest/Programs/php/
