#!/bin/bash
Q1="CREATE TABLE IF NOT EXISTS $1 (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY);"
Q2="SHOW COLUMNS FROM $1;"  
EXPECTED_ARGS=1
E_BADARGS=65
MYSQL=`which mysql`
  
SQL="${Q1}${Q2}"
  
if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: $0 database.table"
  exit $E_BADARGS
fi
  
$MYSQL -u root -p -e "$SQL"
echo $Q1;


