#!/bin/bash
Q1="USE $1;"
Q2="SHOW TABLES";
EXPECTED_ARGS=1
E_BADARGS=65
MYSQL=`which mysql`
  
SQL="${Q1}${Q2}"

  
if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: $0 database.table"
  exit $E_BADARGS
fi
  
$MYSQL -u root -p -e "$SQL"
echo $Q1;
echo $Q2;

