[manager]
show_hidden = false
sort_by = "alphabetical"
sort_dir_first = true

[preview]
max_width = 1000
max_height = 1000
image_quality = 90
sixel_fraction = 15

[opener]
edit = [{ run = 'nvim "$@"', block = true }]
