#
# OpenBoardView configuration
#
# Renderer options
#  1 = OpenGL1
#  2 = OpenGL3
#  3 = OpenGLES2
renderer=2

windowX=1200
windowY=700

# Reference DPI is 100, increase if you have a higher density (ie, small 4K or 2K screen)
dpi=100

fontName = DejaVu Sans
fontSize = 20
showInfoPanel = true
infoPanelWidth = 300
showPins = true
showPosition = true
showNetWeb = true
showBackgroundImage = true
pinSelectMasks = true
pinSizeThresholdLow = 0
pinShapeCircle = true
pinShapeSquare = false

slowCPU =       false
showFPS =       false
pinHalo =       false
pinHaloDiameter = 1.1
pinHaloThickness = 4

fillParts =		true
showPartName =  true
showPinName =  true
boardFill =		true
boardFillSpacing = 3

zoomFactor = 0.5
zoomModifier = 5

panFactor = 30
panModifier = 5

centerZoomSearchResults = true
infoPanelCenterZoomNets = true
infoPanelSelectPartsOnNet = true
partZoomScaleOutFactor = 3.0

# Flip board modes
#  0: flip whole board in view port, shift-flip to flip around mouse ptr
#  1: flip around mouse ptr, shift-flip to flip view port
flipMode = 0

showAnnotations = true
annotationBoxSize = 20
annotationBoxOffset = 8

netWebThickness = 2

pdfSoftwarePath = SumatraPDF.exe
#
# "XRayBlue" Theme by Inflex (20160724)
# Colors, format is 0xRRGGBBAA
#
# There's two built in themes, light (default) and dark 
#colorTheme = default
#colorTheme = dark
colorTheme = light
backgroundColor		= 0xffffffff
boardFillColor	= 0xddddddff
partOutlineColor = 0x444444ff
partHullColor			= 0x80808080
partFillColor = 0xffffff77
partTextColor			= 0x80808080
partHighlightedFillColor = 0xf4f0f0ff
partHighlightedColor = 0xff0000ee
partHighlightedTextColor			= 0xff3030ff
partHighlightedTextBackgroundColor			= 0xffff00ff

# Pin colourings.
#  default is for pins that aren't selected
#  selected is for the actual clicked on pin
#  highlighted is for pins usually on the same network as the selected
#
# There's an absense of 'fill' colours on most because the CPU hit is
# moderately high to do them all 
#
boardOutlineColor			= 0x444444ff
pinDefaultColor				= 0x22aa33ff
pinDefaultTextColor			= 0x666688ff
pinTextBackgroundColor		= 0xffffff80
pinGroundColor				= 0x2222aaff
pinNotConnectedColor		= 0xaaaaaaff
pinTestPadColor				= 0x888888ff
pinTestPadFillColor				= 0xbd9e2dff

pinSelectedColor				= 0x00000000
pinSelectedFillColor			= 0x8888ffff
pinSelectedTextColor			= 0xffffffff

pinSameNetColor			= 0x0000ffff
pinSameNetFillColor		= 0x9999ffff
pinSameNetTextColor		= 0x111111ff

pinHaloColor			= 0x22FF2288

pinNetWebColor = 0xff0000aa
pinNetWebOSColor = 0x0000ff33

annotationPopupTextColor = 0x000000ff
annotationPopupBackgroundColor = 0xeeeeeeff
annotationBoxColor = 0xff0000aa
annotationStalkColor = 0x000000ff

selectedMaskPins		= 0xffffffff
selectedMaskParts		= 0xffffffff
selectedMaskOutline		= 0xffffffff

orMaskPins		= 0x00000000
orMaskParts		= 0x00000000
orMaskOutline	= 0x00000000
# EndColors

# FZKey requires 44 32-bit values in order for it to work.
#  If you have the key, put it in here as a single line, each value comma separated
#FZKey = 0x12345678, 0x12345678
FZKey =   

# END OF CONF

KeyBindingClear = Escape
KeyBindingTogglePins = P
KeyBindingNetList = L
KeyBindingInfoPanel = I
KeyBindingPanRight = D|Keypad6
KeyBindingPanLeft = A|Keypad4
KeyBindingQuit = ModCtrl~Q
KeyBindingPartList = K
KeyBindingPanUp = W|Keypad8
KeyBindingSearch = ModCtrl~F|Slash
KeyBindingOpen = ModCtrl~O
KeyBindingValidate = ModShift~Enter
KeyBindingAccept = Enter
KeyBindingCenter = X|Keypad5
KeyBindingZoomIn = KeypadAdd|Equal
KeyBindingMirror = M
KeyBindingCloseDialog = Escape
KeyBindingRotateCW = R|Period|KeypadDecimal
KeyBindingZoomOut = Minus|KeypadSubtract
KeyBindingRotateCCW = Comma|Keypad0
KeyBindingFlip = Space
KeyBindingPanDown = S|Keypad2