alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ln='ln -i'
alias ls='ls --color=auto'
alias l='ls -CF'
alias ll='ls -lAh'
alias la='ls -A'
alias lt='ls -lAhtr'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ~='cd ~'
alias -- -='cd -'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias c='clear'
alias h='history'
alias q='exit'
alias t='tmux'
alias ta='tmux attach -t'
alias tn='tmux new -s'
alias tl='tmux list-sessions'
alias mkdir='mkdir -pv'
alias df='df -h'
alias du='du -ch'
alias free='free -h'
alias ip='ip -c'
alias explorer='explorer.exe .'
alias open='explorer.exe'
alias pbcopy='clip.exe'
alias pbpaste='powershell.exe -Command Get-Clipboard'
alias npm='bun'
alias npx='bun'
alias reload='exec bash'
